.TH MYSHELL 1 "April 2025" "Version 1.0" "User Commands"
.SH NAME
man_1_simple_shell \- a simple custom command line
.SH SYNOPSIS
.B man_1_simple_shell command-line interpreter that executes user commands. It supports basic functionality such as
executing binaries from the system path, handling environment variables, and basic command parsing. This is the final project for the first trimester from 
.B Cohort 26 Ponce.

.SH RUNNING PROGRAM

Run the program by typing
.B /hsh
on the terminal.

Theen press 
.B [Enter]

.SH LIBRARIES USED
#include <stdio.h>
.br
#include <stdlib.h>
.br
#include <unistd.h>
.br
#include <stddef.h>
.br
#include <string.h>
.br
#include <sys/wait.h>
.br

.SH OPTIONS
There are no specific options for
.B man_1_simple_shell



$ ./man_1_simple_shell myscript.sh

.SH AUTHOR
Written by Paola N. Gonzalez Melendez

.Sh BUGS
No known bugs. Report issues to 10345@holbertonstudents.com

.SH COPYRIGHT
This is a free software. You may copy under permission of its author.

 

 